/// Flutter icons CryptoIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CryptoIcons
///      fonts:
///       - asset: fonts/CryptoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CryptoIcons {
  CryptoIcons._();

  static const _kFontFam = 'CryptoIcons';
  static const String? _kFontPkg = null;

  static const IconData bot = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btc = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discount = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drop_down = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exchange = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notifications = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData services = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_change = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wifi = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
